# Set basic options ------------------------------------------------------------
baseurl = "/"
title = "leachjim - Jim Leach's blog" # The page title (e.g. in FF tabname)
languageCode = "en-us"
paginate = 5 # Number of posts per page
preserveTaxonomyNames     = true
enableEmoji               = true
uglyURLs                  = false
publishdir                = "public"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"] # Add ignore files as advised by blogdown


# Comments / tracking options --------------------------------------------------
# Add a disquss profile to enable comments
# disqusShortname = "spf13"
# Enable Google Analytics be inserting your tracking code
# googleAnalytics = ""


# Theme options ----------------------------------------------------------------
theme = "hugo-steam-theme"
[params]
	title = "leachjim" # The title on the page
	subtitle = "a personal website for Jim Leach" # The subtitle on the page
	#copyright = "MIT."

	# You can choose between green, orange, red and blue.
	themecolor = "blue"

	# Link custom assets relative to /static
	#favicon   = "favicon.ico"
	customCSS = []
	customJS  = []

	# To provide some metadata for search engines and the about section in the footer
	# feel free to add a few information about you and your website.
	name = "Jim Leach"
	bio = "data scientist, R programmer, a Briton abroad"
	#description = "The personal website of "
	
	# Link your social networks (optional)
	twitter = "leach_jim"
	linkedin = "jim-leach-77028b59"
	github = "jim89"

	# Customize or translate the strings
	keepReadingStr = "Keep reading"
	backtotopStr = "Back to top"
	shareStr = "Share"
	pageNotFoundTitle = "Sorry; page not found"
