# Set basic options ------------------------------------------------------------
baseURL                   = "https://censor-ronald-60453.netlify.com/"
title                     = "the data gent"
description               = "data science, data analysis blog" # A brief description of your website. It is not visible on web pages (you can only see it from the HTML source), but should give search engines a hint about your website.  
copyright                 = ""
theme                     = "minimo"
disqusshortname           = "thedatagent" # Comment out to disable Disqus.
googleAnalytics           = ""
Paginate                  = 5
preserveTaxonomyNames     = true
ignoreFiles               = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"] # Add ignore files as advised by blogdown
enableEmoji               = true
uglyURLs                  = false

# Add option for perma links
[permalinks]
  page = "/:slug/"
  blog = "/:year/:month/:day/:slug/"  
  
  
# Add main menu values ---------------------------------------------------------
# Don't need anything here for now - anything in content directory with the menu
# parameter set to 'main' will pop up in the menu bar!

# Set specific parameters ------------------------------------------------------
[params]
  description = "data science; in plain english"
  dateFormat = "2006/02/01"
  copyrightOwner = "Jim Leach"
  copyrightStartYear = "2017"
  favicon = "favicon.ico"
  hideEntryNavigation = false
  customCSS = ["css/custom.css"]
  customJS = ["js/custom.js"]
  hideSocialMenu = false
  showReadTime = true
  
# Highlight functions
  highlightjs            = true
  highlightjslanguages   = ["r", "yaml", "bash"]                        # additional languages not included in the "common" set
  # highlightjsStyle     = "darcula"  

[params.seo]
  # Title Separator: - – — · • * ⋆ | ~ « » < >
  titleSeparator = "•"

[params.opengraph]
  [params.opengraph.facebook]
    admins = ""
    appid = ""

[taxonomies]
  category = "categories"
  tag = "tags"

[social]
  facebook = ""

[author]
  name = "Jim Leach"

[author.social]
  email = "jimmy22theave@gmail.com"
  github = "Jim89"
  twitter = "leach_jim"
  linkedin = "jim-leach-77028b59"  
  
  # Not used:
  #instagram = "instagram"  
  #facebook = "MunifTanjim"
  #codepen = "MunifTanjim"
  


# Language Configuration -------------------------------------------------------
defaultContentLanguage = "en"
[languages]
  # edit this block for your own language
  [languages.en]
    lang = "en"
    languageName = "English"
    weight = 1




