---
title: Thoughts on the EARL conference
date: '2015-10-01'
slug: earl-conference-2015
categories:
  - R
  - Data Science
tags: []
description: "I went to the EARL conference and had a great time, this post summarises some of my thoughts from the conference"
---

The [EARL](http://www.earl-conference.com/index.html) conference is one of the largest conferences focussed on commercial applications of 'R'. A couple of weeks ago I was honoured to attend as a speaker as one of my last activities at work before starting my MSc. I want to jot a few thoughts down here on what I liked about my experience. Side note: I was only in attendance for the first day of talks, and I did not attend any of the workshops.

<blockquote class="twitter-tweet" data-lang="en-gb"><p lang="en" dir="ltr">data science on the back of a lunch napkin. only at <a href="https://twitter.com/hashtag/earl2015?src=hash">#earl2015</a></p>&mdash; Jim Leach (@leach_jim) <a href="https://twitter.com/leach_jim/status/643790708827140096">15 September 2015</a></blockquote>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>

This was my second EARL (I also attended the inaugural event last year) and I'm pleased to report that this year was just as good if not better than last year's. The organisers, [Mango Solutions](http://www.mango-solutions.com/), did an excellent job putting it all together. They deserve much credit for starting a conference with such an important focus. (Too many conferences, in my view, focus on the purely technical and overlook the purpose/applications of the technology).

## The speakers

<blockquote> Keep it simple and explain what you are doing </blockquote>

An colleague recently shared an article on the [top 9 languages for crunching data](http://www.fastcompany.com/3030716/the-9-best-languages-for-crunching-data). A commenter humorously added: "Let's start with English, keep it simple explain what you are doing". This really resonated with me and got me thinking again about the speakers at EARL. I'm pleased to report that the vast majority that I saw stuck to this and as a result I left the conference enthused and feeling more excited about data than ever before. 

The morning started with Markus Gesmann ([mages' blog](http://www.magesblog.com/)) who gave a clear and interesting talk about risk and how his team uses `R` for assessing probabilities in the insurance industry. It prompted several interesting questions (more on that later) and Markus demonstrated the benefits of clear and simple explanation in his responses.

The second talk (my favourite of the conference) was from Amar Dhand, a doctor and professor from St. Louis. Prof. Dhand gave a fascinating talk on how he and his team are using `R` for [social network analysis and how it relates to stroke recovery](http://publichealth.wustl.edu/projects/social-networks-stroke-recovery/). The results were amazing and communicated brilliantly. Prof. Dhand pitched his talk perfectly with just the right amount of detail for the (non-doctor) audience. In other words, he kept it simple and explained what he'd been doing. The rest of the audience was clearly as impressed as I was and I'll be keeping an eye on his research in the future. 

In the afternoon I attended the visualisation session. Here I heard an interesting talk from David Ruau on his challenges working in the pharmaceutical industry. He and his team are working towards solutions with `R` and Shiny. My colleague and I were particularly jealous when he revealed how much time his team was given to develop such solutions (by a consultant's standard: <b>a lot</b>). There was also an interesting talk on mapping in `R` from James Cheshire who found fame with his excellent [book](http://theinformationcapital.com/) and blogs at [spatial.ly](http://spatial.ly/). James talked about his experiences working with `R` and gave some tips for using it to create maps. As I've played around with some maps myself this talk was very useful and gave some food for thought for my own projects. 

In the final session there was a brilliant talk from Mark Sellors from Mango. Mark is a data engineer and gave a brilliant talk about [`SparkR`](https://amplab-extras.github.io/SparkR-pkg/). He clearly articulated what he sees as the positives to using Spark with `R`, as well as some of the challenges. As someone who's just getting started with technologies like Spark, this talk was excellent. Mark also pitched his talk very well and I felt simultaneously engaged and educated. Yet again, demonstrating the value of clarity of explanation.


## The listeners

As well as talking about some of the excellent speakers at EARL, I thought it was also worth mentioning the other side of the conference: the other attendees. Mango did a great job of getting a broad mix of people. Some were very technical, engineering types; some were non-technical, business-oriented folk, and some were somewhere in between. 

Similar to the audience make up, the questions following the talks were a pleasing mix of technical and business focussed. This breadth kept things interesting as discussions never felt too detailed nor too high level. Our own talk seemed to be well received, with several insightful questions afterwards around how we had accounted for some of the probabilistic properties of our model, and a couple of technical questions about our choice of approach.

More broadly, I had several great conversations during the networking sessions. One with a chap who worked in HR went on for a while whilst we chatted about how he could approach some of his data-challenges. It was interesting to see how techniques I've learned and developed over the last few years can be applied to a new situation. I also had a good talk with some of the Mango technical team about Docker (which I'd be basically clueless on up to then) and its applications in a consulting environment. All in all a great mix of great people!

## Overall

To sum up, EARL was well worth the ticket price and I'd highly recommend it for anyone interested in data science and/or `R`. The majority of talks were interesting, well presented and stimulated some really interesting discussions. Mango have done an excellent job with this conference and I'm glad to see it going so well. The focus of this conference is an important one. Too often we can get bogged down in the technical details of data science, or too lost in the hype and the jargon. EARL is a great antidote to those problems, walking the middle path of clarity and simplicity of explanation coupled with great enthusiasm and passion for an exciting subject. Well done Mango.
