---
title: MSc Analytics Introduction
date: '2015-10-22'
slug: msc-analytics-intro
categories:
  - Uncategorised
tags: []  
---

I've recently started my [MSc. in Analytics](http://wwwf.imperial.ac.uk/business-school/programmes/msc-business-analytics/) at Imperial College London and, as I'm hoping to post some updates throughout the year about the course, I thought I'd give it a quick introduction here. 

I'll talk about my motivations for doing the course, and give a quick run down of what I can expect for the year. The course is administered by the Business School and delivered in partnership with the Computer Science Department, and the [Data Science Institute](https://www.imperial.ac.uk/data-science/).

> "This highly practical one year programme will equip graduates to drive business advantage using key analytical methods and tools"

## My motivations

Given that I have several years' experience in this field, I've been asked a few times why I've decided to come back and study. My answer has been relatively simple: after 3 years' at the same company it felt like time for something new. I'm naturally curious and love learning and the combination of these things made further study seem like an obvious solution. I had a chat with my mentor (who blogs [here](http://guerrilla-analytics.net/posts/)) and he suggested a masters program. I did some research, found this course, and the rest is history.

## The course

### Content:

The course is designed around teaching the practical skills and knowledge necessary for working in data science and I think the core modules reflect this. Over the year I'll be studying:

* The principles of data science in the workplace;
* Advanced analytics and machine learning;
* Network analytics;
* Data visualisation;
* Databases and distributed systems
* Statistics and econometrics; and
* Optimisation and decision models.

There are also a number of electives covering introductions to various industries (e.g. healthcare, finance, digital marketing etc) and the application of the practical techniques (taught in the core modules) to solve problems in these industries. There's lots of data for practising and refining techniques flying about, kindly contributed from ongoing research at Imperial and from members of the programmes advisory board.

### Design

The course was designed in partnership with an "Advisory board" of companies including Thompson Reuters, KPMG, IBM, The Boston Consulting Group, Dunhumby and [many more](http://wwwf.imperial.ac.uk/business-school/programmes/msc-business-analytics/advisory-board/). The idea behind this is to make the course as relevant and targeted as possible and so far it seems to have paid off. I reviewed some other programs elsewhere but nothing else felt quite as well-put-together as the offer from Imperial.

I'm looking forward to the course, the other students I've met seem similarly excited by it, and I'm keen to get back to some full time study. Check back soon for some updates on what I've been getting up to!
